### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by GotaloveCode** [mohamedsabil83/filament-forms-tinyeditor#100]
### What happened?

Not a bug but I cant request feature. Thanks for the great package

Missing in the doc if using filament forms standalone include this step. 
php artisan vendor:publish --tag="filament-forms-tinyeditor-assets"
Also if using filament forms standalone skip step: 
php artisan filament:assets

### How to reproduce the bug

Install on standalone filament forms using steps.

### Package Version

2.0.0

### PHP Version

8.1

### Laravel Version

9.0.0

**Comment by mohamedsabil83** [comment]
Thank you, @GotaloveCode, for mentioning that. Also, I'm glad the package is useful for you.

When installing the **filament forms**, the developer will run the `php artisan filament:install --forms` in new or existing projects, which adds the `filament:upgrade` command to the **composer.json**. This command will auto-publish the assets.

**FMI:** [Read here](https://filamentphp.com/docs/3.x/forms/installation#upgrading)
