### ISSUE TITLE
[Bug]: Undefined variable $getHintAction

### ISSUE THREAD

**Issue by core45** [mohamedsabil83/filament-forms-tinyeditor#108]
### What happened?

PHP 8.2.11
Laravel 10.29.0
Filament 3.0.85
filament-forms-tinyeditor 2.0.9

I installed and changed the standard Filament's RichEditor (RichEditor works fine) to TinyEditor I get this error:

`Undefined variable $getHintAction`

`[resources / views / vendor / filament-forms-tinyeditor / tiny-editor.blade.php `

### How to reproduce the bug

just install it and try to use it as described in the docs

### Package Version

2.0.9

### PHP Version

8.2.11

### Laravel Version

10.29.0

### Which operating systems does with happen with?

macOS

**Comment by mohamedsabil83** [comment]
Mainly, you published the view file since v1. In v2, the view file changed. So, delete the view file or force re-publish it and re-apply any modification you did before.

**Comment by core45** [comment]
This worked and now it's perfect. Thank you!

**Comment by mohamedsabil83** [comment]
You're welcome
