### ISSUE TITLE
Not compatible with panel spa ->spa()

### ISSUE THREAD

**Issue by majdghithan** [mohamedsabil83/filament-forms-tinyeditor#109]
### What happened?

I entered the edit or create records page but the editor will not be shown

### How to reproduce the bug

use ->spa() on the panel

### Package Version

2

### PHP Version

8.1

### Laravel Version

10.10

### Which operating systems does with happen with?

macOS, Windows, Linux

**Comment by mohamedsabil83** [comment]
Any specific issues in the console? It works as expected on my side.

**Comment by majdghithan** [comment]
<img width="1437" alt="Screenshot 2023-11-04 at 17 31 53" src="https://github.com/mohamedsabil83/filament-forms-tinyeditor/assets/54972678/37c3b76a-5238-48a1-b963-c4eec28335ce">

**Comment by mohamedsabil83** [comment]
It's a livewire issue. The SPA is still experimental and not stable enough, which is why it could lead to different results.
You can see the warning on enabling **SPA** in [Filament docs](https://filamentphp.com/docs/3.x/panels/configuration#spa-mode)
