### ISSUE TITLE
[Bug]: Image saved in db doesn't work while edit works

### ISSUE THREAD

**Issue by mateo-it** [mohamedsabil83/filament-forms-tinyeditor#113]
### What happened?

I'm trying to upload image using:
`TinyEditor::make('content')
  ->fileAttachmentsDisk('local')
  ->fileAttachmentsVisibility('public')
  ->fileAttachmentsDirectory('public')`

Path saved in db is: ../../storage/ while it needs to be either /storage or ../../../storage.
I'm using Laravel 10 and filament v3.

Is this expected, or I need to adjust path before saving in database?
P.S. When using edit feature, it correctly uploads and saves as : ../../../storage.

Thank you!

### How to reproduce the bug

When I upload image in tinymce text editor it saves wrong path in database, while on edit works as expected.

### Package Version

2.1

### PHP Version

8.2

### Laravel Version

10

### Which operating systems does with happen with?

Windows

**Comment by mohamedsabil83** [comment]
Try change **relativeUrls** / **convertUrls**. It may work for you.

**Comment by mateo-it** [comment]
> Try change **relativeUrls** / **convertUrls**. It may work for you.

Thanks! It works when I set relative urls to false.

Thank you!

**Comment by mohamedsabil83** [comment]
You're welcome

**Comment by muath-ye** [comment]
> Try change **relativeUrls** / **convertUrls**. It may work for you.

Thank you it worked for by adding `->setConvertUrls(false)` to the component

**Comment by mohamedsabil83** [comment]
You're welcome
