### ISSUE TITLE
[Bug]: Copy-paste bullet points not working correctly in Chrome Browser 

### ISSUE THREAD

**Issue by UshurbakiyevDavlat** [mohamedsabil83/filament-forms-tinyeditor#117]
### What happened?

I trying to copy and paste bullet pointed text from MS Word , but it does not work but if I copy-paste from GoogleDocs or Pages in MacOS it works well.

### How to reproduce the bug

- Copy any bulleted text in MS Word
- Try to paste it in editor form

### Package Version

2.0

### PHP Version

8.2.0

### Laravel Version

10.31.0

### Which operating systems does with happen with?

Windows

### Notes

I googled for the problem but there only says that need to buy some premium version of tiny mce.

**Comment by mohamedsabil83** [comment]
Yes, this is related to the editor itself, not the plugin. Some features need premium plugins from them. You can try to contact them for more advice.
