### ISSUE TITLE
Uploaded image not deleted

### ISSUE THREAD

**Issue by diazsasak** [mohamedsabil83/filament-forms-tinyeditor#12]
Hi,

when i upload image and then delete the record. the image still exists in the storage. any help?

thank you in advance

**Comment by mohamedsabil83** [comment]
Hi,

The concept of uploading an image(s) in any of the three editors is saving the image then returning the path as plain text within the editor, not attach to the model. So, when deleting the model, it can't figure if there are any images to delete as their paths are saved as plain text.

FMI, you can take a look at the [HasFileAttachments Trait](https://github.com/laravel-filament/filament/blob/2.x/packages/forms/src/Components/Concerns/HasFileAttachments.php) which is used by all three editors.

**Comment by diazsasak** [comment]
Hi @mohamedsabil83 ,

is that mean this package can use that trait to solve this problem or I need to use the official filament text editor?

**Comment by mohamedsabil83** [comment]
The upload processing is done by the mentioned trait in my previous comment. You can review the filament admin for more info.
