### ISSUE TITLE
[Bug]:  The fullscreen mode is not working properly

### ISSUE THREAD

**Issue by tok3** [mohamedsabil83/filament-forms-tinyeditor#121]
### What happened?

When the editor is opened in fullscreen mode (in my case opened from a builder block), the toolbar is always covered by the left navigation of Filament3. Unfortunately, no way has been found to increase the z-index accordingly. All hints regarding the same issue in connection with Twitter Bootstrap have been tried without success. 

### How to reproduce the bug

Open editor in fullscreen mode

### Package Version

2.3.1

### PHP Version

8.2.7

### Laravel Version

10

### Which operating systems does with happen with?

macOS

**Comment by mohamedsabil83** [comment]
It seems you made a custom theme, including Bootstrap, if I understand you will. But I checked on my side inside/outside the builder, and fullscreen works as expected.
Can you provide extra details, e.g., use it within the panel or forms only? Also, a screenshot will be helpful.

**Comment by tok3** [comment]
Hello Mohamed, thank you for the quick response.

I'm using it in filament panels in builder block. The content_css I load in the TinyMCE config is Bootstrap. I don't use Bootstrap in Filament itself; it's all Tailwind as it comes with Filament. As you can see in the second screenshot, the left navigation is over the TinyMCE content, and thus over the button controls, meaning that all buttons lying under the navigation cannot be pressed. In this example, from fullscreen to link. Sometimes, as in the last screenshot, the menu does not appear at all in fullscreen mode, then it seems to lie under the top bar.
Do you have any idea what might be causing this, or any suggestions?



Am 21. März 2024, 19:57 +0100 schrieb Mohamed Sabil ***@***.***>:

**Comment by mohamedsabil83** [comment]
Hello, @tok3.

Unfortunately, the screenshots are not attached. But from what you mentioned, It looks like the loaded Bootstrap overrides something in the editor itself, not the plugin.
Could you check the TinyMce 5 docs? You may find some configurations to load **content_css** without any unexpected side effects.

**Comment by tok3** [comment]
The screenshots :-)
<img width="1233" alt="Attachment-1" src="https://github.com/mohamedsabil83/filament-forms-tinyeditor/assets/6725427/8845004f-9b0c-4684-90c7-08bb095f240c">
<img width="1352" alt="Attachment-2" src="https://github.com/mohamedsabil83/filament-forms-tinyeditor/assets/6725427/830516af-8293-466e-8fc7-29053ca6aee9">
<img width="1290" alt="Attachment" src="https://github.com/mohamedsabil83/filament-forms-tinyeditor/assets/6725427/29c4331f-6cd5-4a28-8c41-1b9e97fb57b4">

**Comment by mohamedsabil83** [comment]
Could you stop loading **content_css** and check if **fullscreen** works as expected? From the attached screenshots, it's clear that you don't use a custom theme for the panel. So, if it works after stopping loading **content_css**, then you can focus on that part.

**Comment by tok3** [comment]
Unfortunately the same behavior
 
![Bildschirmfoto 2024-03-22 um 12 45 17](https://github.com/mohamedsabil83/filament-forms-tinyeditor/assets/6725427/2d90ebda-1909-4bd0-a236-6bc27402e570)

**Comment by mohamedsabil83** [comment]
That's weird. I tried again on my side, and it works as expected.
Run the command `php artisan filament:upgrade` and ensure your dependencies are updated and you didn't publish/override something that made this happen.

**Comment by mohamedsabil83** [comment]
OK. I'll close it for now, but please don't hesitate to re-open it if you find anything new.
