### ISSUE TITLE
[Bug]: Images are not deleting from livewire temporary folder

### ISSUE THREAD

**Issue by Matvik** [mohamedsabil83/filament-forms-tinyeditor#124]
### What happened?

I see uploaded images in /storage/app/livewire-tmp path after uploading. How can i configure it to move, not to copy?

### How to reproduce the bug

Upload image in editor

### Package Version

2.3.1

### PHP Version

8.2.16

### Laravel Version

10.48.4

### Which operating systems does with happen with?

Linux

**Comment by mohamedsabil83** [comment]
Your question is related to Livewire. By default, all temp files inside the **livewire-tmp** folder that take more than a day will be removed automatically.

**Comment by Matvik** [comment]
Thank you, i am really new in livewire)
