### ISSUE TITLE
[Bug]: Text not editable with filament outerweb/filament-translatable-fields

### ISSUE THREAD

**Issue by fklee** [mohamedsabil83/filament-forms-tinyeditor#129]
### What happened?

When using spatie/laravel-translatable with filament translatable plugins (outerweb/filament-translatable-fields) the text in the tinymce is empty.

### How to reproduce the bug

Install Filament
Install spatie/laravel-translatable
Install outerweb/filament-translatable-fields
Install filament/spatie-laravel-translatable-plugin

set a field as "`->translatable()`"

### Package Version

2.0.0

### PHP Version

8.1.0

### Laravel Version

10.48.0

### Which operating systems does with happen with?

Linux

**Comment by mohamedsabil83** [comment]
I don't think these combinations work on the same resource/page. You must use either **filament/spatie-laravel-translatable-plugin** or **outerweb/filament-translatable-fields**.

If you find a workaround, don't hesitate to make a PR.
