### ISSUE TITLE
[Bug]: Inline mode not working for me.

### ISSUE THREAD

**Issue by willcastillo** [mohamedsabil83/filament-forms-tinyeditor#131]
### What happened?

There's not a way to activate the inline mode via the plugin. Even if I extend the plugin class and add the getter/setter for this property (and conditionally remove the `content_css` prop) there are some js errors popping up and the editor doesn't load.

```Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive.```

### How to reproduce the bug

Just try to active the inline mode.

### Package Version

2

### PHP Version

8.2

### Laravel Version

11

**Comment by mohamedsabil83** [comment]
Hi @willcastillo. The only supported mode is the default one. I'll see if I add some or all modes in the new major release which will adopt the latest version of TinyEditor.
