### ISSUE TITLE
[Bug]: Unable to input content when used with Filament's FileUpload

### ISSUE THREAD

**Issue by timomedia** [mohamedsabil83/filament-forms-tinyeditor#134]
### What happened?

When I use your library together with Filament v2 FileUpload field, I can no longer input content in the text editor.
Additionally, when I use the original edit form, the editor field doesn't load the TinyMCE editor anymore. You can see this in the video below.

https://github.com/user-attachments/assets/5011eb6a-acc5-4cc4-9c0c-6214900019ec

### How to reproduce the bug

Here is the code for creating my form
```
FileUpload::make('image')
                ->label('Image')
                ->image()
                ->preserveFilenames()
                ->maxSize(1024)
                ->maxFiles(1),
TinyEditor::make('content')
      ->label('Nội dung')
      ->profile('simple')
      ->language('en')
      ->fileAttachmentsDisk('local')
      ->fileAttachmentsVisibility('public')
      ->fileAttachmentsDirectory('uploads')
      ->required(),
```
I suspect that jQuery is either failing to load or loading too late, causing the data not to display or to be overwritten. Is there a way to handle this?
Please help me.
Thank you so much!

### Package Version

1.7

### PHP Version

8.3

### Laravel Version

10.0

**Comment by mohamedsabil83** [comment]
Hello, sorry for the late response. V1 is not maintainable anymore. But, any PR is welcome.
