### ISSUE TITLE
Uploaded image use wrong URL

### ISSUE THREAD

**Issue by diazsasak** [mohamedsabil83/filament-forms-tinyeditor#14]
Hi,

I have upload image in the content. Then it successfully saved. But when I go to the edit page it use wrong URL:

http://local.dev/admin/storage/sDaZKcLKYCG0pCScdKwTIba3p3PBrhdoovCqoMEC.jpg

the right URL is http://local.dev/storage/sDaZKcLKYCG0pCScdKwTIba3p3PBrhdoovCqoMEC.jpg . without /admin

Any solution?

Thank you in advance

**Comment by mohamedsabil83** [comment]
Try to check your **filesystems** config and the **APP_URL** in the **.env** file.

**Comment by SerhiiStarovoitov** [comment]
@diazsasak, add _document_base_url_ to _custom_configs_ in _config/filament-forms-tinyeditor.php_ (you need to publish config first if you have not done it before).

```
'custom_configs' => [
  'document_base_url' => config('app.url'),
]
```
