### ISSUE TITLE
tinymce.min.js script load twice

### ISSUE THREAD

**Issue by t7team** [mohamedsabil83/filament-forms-tinyeditor#17]
tinymce.min.js script load twice

- One time from provider.
- Second time from blade component.

Script should load once and only when it is used.

**Comment by mohamedsabil83** [comment]
The package was built to work with both **FilamentAdmin** and **FilamentForms**. This behavior is because **Livewire** does not support **@puch** when late rendering. **Caleb** plans to support that. until then, according to your project, you can publish the view and remove the **@push**  part.
