### ISSUE TITLE
How about source code ? 

### ISSUE THREAD

**Issue by erenergul** [mohamedsabil83/filament-forms-tinyeditor#18]
Hi , How can we see source code ? How can we add on toolbar?

**Comment by mohamedsabil83** [comment]
Hi,

To use any additional open-source plugins of TinyEditor5, you can do the following:
- Publish the config file.
- In the config, add a new profile (or modify the current) by setting the required plugins and toolbar buttons.
- Use method `->profile('your-profile-name')` with Tinyeditor field.

Again, be sure to use open-source plugins which belong to TinyEditor 5.
