### ISSUE TITLE
GET http://www.project.local/admin/blocks/1/ net::ERR_ABORTED 500 (Internal Server Error)

### ISSUE THREAD

**Issue by elfeffe** [mohamedsabil83/filament-forms-tinyeditor#21]
It tried to make a GET call every time I load the page.
Is that normal?

**Comment by mohamedsabil83** [comment]
You didn't provide any details and screenshots to check if that issue came from the package or related to something else

**Comment by elfeffe** [comment]
Sorry:
My URL is:
http://www.commerce.local/admin/blocks/1/edit

This is the screenshot:
https://gyazo.com/594868e29bae80a474b79986728a5f4b

My code:
```
TinyEditor::make('contents')
                    ->showMenuBar()
                    ->columnSpan(4)
```

**Comment by mohamedsabil83** [comment]
It's a local URL not displayed for me. Also, the returned error message was not helpful.
- Did you follow the [installation](https://github.com/mohamedsabil83/filament-forms-tinyeditor#installation) correctly?
- If you didn't publish the assets, do it.

**Comment by elfeffe** [comment]
Enable where?
Filament or your package?
In your package I don't see how to enable it.
In Filament it's enabled.

**Comment by mohamedsabil83** [comment]
Yes, I mean in Filament. Don't know why the line you mentioned before caused the issue. I tried to re-implement the issue but all works fine.
