### ISSUE TITLE
We can not edit the source code in popup

### ISSUE THREAD

**Issue by nchatzidakis** [mohamedsabil83/filament-forms-tinyeditor#22]
Hello,

we added the plugin code (in plugins and toolbar config - default profile).

Although the button appeared and we are able to click it, in the popup we are unable to edit the source code. It seems like a css bug.

**Comment by mohamedsabil83** [comment]
It's a good practice to provide a code and/or screenshot to trying re-implement the issue.

In general, for additional plugins, you have to check the [TinyMce Docs](https://www.tiny.cloud/docs/) about how to set the plugin and if it needs extra files to add to your project.

**Comment by nchatzidakis** [comment]
After some debugging, I noticed that although it works fine when editing a resource, it has issues when editing relations.

In my case, I have a VehicleResource that connects to many VehicleLocaleResource, the tinymce textarea is in VehicleLocaleResource.

So when I edit the VehicleLocaleResource from the VehicleResource page, the popup is not working. I will share some code.

**Comment by mohamedsabil83** [comment]
If you still have this issue we can re-open it
