### ISSUE TITLE
Content disappears after reordering in a repeater

### ISSUE THREAD

**Issue by SebastiaanKloos** [mohamedsabil83/filament-forms-tinyeditor#23]
![CleanShot 2022-06-17 at 11 58 55](https://user-images.githubusercontent.com/6506510/174276099-90bd033a-f878-49f5-a191-702638ee4f22.gif)

**Comment by mohamedsabil83** [comment]
are there any errors appearing in the console?

**Comment by mohamedsabil83** [comment]
Yeah, maybe I notice something. Also, I guess it may be related to the mechanism of the livewire and may be solved by identifying it with something like **wire:key**. I'll check about it and the way that repeater work.

**Comment by SebastiaanKloos** [comment]
@mohamedsabil83 I guess it has to do with the dom being changed, but the state is still the same

**Comment by mohamedsabil83** [comment]
I dig about it and I guess the issue because TinyEditor does not support drag & drop
