### ISSUE TITLE
Editor doesn't render in Firefox

### ISSUE THREAD

**Issue by emohamed** [mohamedsabil83/filament-forms-tinyeditor#28]
Here is the form schema:

```
 public static function getFormSchema(): array
    {
        return [
            Card::make()
                ->schema([
                    Forms\Components\FileUpload::make('image')->image()->maxSize(4096)->label('Avatar'),
                    TinyEditor::make('content'),
                    TextInput::make('author_name')->required(),
                    TextInput::make('author_listings')->required(),
                ]),
        ];
    }
```

The field is rendered correctly in Chrome, however, it doesn't load in Firefox:

![image](https://user-images.githubusercontent.com/536840/187227255-3e24bc8f-ad34-4f97-800d-b374ff637182.png)

**Comment by heloufir** [comment]
The same in chrome, I just installed it on a new project using only Filament Forms, and it's not rendering, but in another project using Filament Admin it's working

**Comment by mohamedsabil83** [comment]
Do you update firefox to the latest release? Fixed for someone before when he update his firefox
