### ISSUE TITLE
Getting error no templates found even when i have templates defined in config file

### ISSUE THREAD

**Issue by khanakia** [mohamedsabil83/filament-forms-tinyeditor#31]
I can see i have the templates already in `config/filament-forms-tinyeditor.php`

<img width="621" alt="Screenshot 2022-09-12 at 4 52 20 PM" src="https://user-images.githubusercontent.com/2174170/189641306-4ac2e3d1-2733-4c61-adc9-51bc55176fa2.png">

**Comment by mohamedsabil83** [comment]
can you share the code to re-implement your issue?

**Comment by khanakia** [comment]
I got it fixed i had to pass the template param `TinyEditor::make('content')->template('example')`

Can you please add these points to the documentation so for any new user it will be easy to know how to use it instead of debugging the code.
