### ISSUE TITLE
Undefined variable $getHintAction

### ISSUE THREAD

**Issue by mark-the-spark** [mohamedsabil83/filament-forms-tinyeditor#50]
I get an error "Undefined variable $getHintAction" when trying to use in Filament admin panel. 

The editor is being use like the below: 

`TinyEditor::make('body')->height(900)->required()->label('Editor')->reactive()`

Commenting out the lines below in tiny-editor.blade.php fixes the issue. 
```
:hint-action="$getHintAction()"
:hint-color="$getHintColor()"
:hint-icon="$getHintIcon()" 

```

**Comment by mohamedsabil83** [comment]
Be sure you are updating both **Filament** and **This Plugin** to the latest version and clear the view cache

**Comment by mark-the-spark** [comment]
You're a hero! Was on Filament 2.16.0 and upgrading to 2.16.58 fixed the issue.

**Comment by mohamedsabil83** [comment]
Glad to hear that.
