### ISSUE TITLE
Using server side file/image browser

### ISSUE THREAD

**Issue by michael-grunewalder** [mohamedsabil83/filament-forms-tinyeditor#52]
It's not a bug report, but the other options were not working for me.

What I would like to do is use a server side file/image browser (e.g. https://unisharp.github.io/laravel-filemanager/) to insert images. How can I achieve that? So far I managed to show the media browser, but selecting any file does not have any affect, does not display the image in my text.

Thanks in advance.

**Comment by mohamedsabil83** [comment]
Try to check how to integrate the mentioned package with the TinyEditor, then, publish the view file and make the required changes to it
