### ISSUE TITLE
[Bug]: Uncaught TypeError: Cannot read properties of null (reading 'setAttribute')

### ISSUE THREAD

**Issue by theia-kevin** [mohamedsabil83/filament-forms-tinyeditor#62]
### What happened?

Javascript errors occured after opening the table properties window.

### How to reproduce the bug

Draw a table > Open Table Properties

### Package Version

^1.7

### PHP Version

8.1.15

### Laravel Version

^9.19

### Notes

I'm not sure whether it's got anything to do with Alpine Focus, because I did a quick console.log and noticed

https://github.com/mohamedsabil83/filament-forms-tinyeditor/blob/1b5edd60b4107ef1e0a5ef20782cf41ee7d98b63/resources/views/tiny-editor.blade.php#L65

https://github.com/mohamedsabil83/filament-forms-tinyeditor/blob/1b5edd60b4107ef1e0a5ef20782cf41ee7d98b63/resources/views/tiny-editor.blade.php#L69

`e.target.container.closest('.filament-modal')` is returning `null`

**Comment by diazsasak** [comment]
I got the same error too when opening table properties, all table properties features not working

**Comment by mohamedsabil83** [comment]
Fixed in **v1.7.1**

**Comment by diazsasak** [comment]
@mohamedsabil83 Thank you! its work

**Comment by mohamedsabil83** [comment]
You're welcome
