### ISSUE TITLE
[Bug]: Problem with loading the tinymce.min.js asset

### ISSUE THREAD

**Issue by poldixd** [mohamedsabil83/filament-forms-tinyeditor#64]
### What happened?

Filament should load the tinymce.min.js asset. But I'm getting a 404 error.

<img width="550" alt="Bildschirm­foto 2023-03-23 um 21 08 20" src="https://user-images.githubusercontent.com/695449/227340389-d71474c2-a64a-4ee7-a161-e5e787484976.png">

### How to reproduce the bug

When you install your plugin in filament and you go to the page where the editor is included.

### Package Version

1.7.1

### PHP Version

8.2.4

### Laravel Version

10.4.1 

### Which operating systems does with happen with?

macOS

### Notes

Maybe the error is here: https://github.com/mohamedsabil83/filament-forms-tinyeditor/blob/main/src/FilamentFormsTinyeditorServiceProvider.php#L45

If you change the path to…

```php
'filament-forms-tinyeditor' => asset('vendor/mohamedsabil83/filament-forms-tinyeditor/resources/dist/tinymce/tinymce.min.js'),
```

… filament will find the right asset file and send it to the browser. In [this](https://github.com/filamentphp/filament/blob/2.x/packages/admin/src/Http/Controllers/AssetController.php#L58) function filament checks if the asset file exists in the composers vendor directory. If the file is not exists, filament will throw a 404.

**Comment by nguyentranchung** [comment]
> Next, publish the asset by run the following:
> 
> php artisan vendor:publish --tag="filament-forms-tinyeditor-assets"

**Comment by poldixd** [comment]
Sry, I forgot to write: the assets was published.

**Comment by nguyentranchung** [comment]
<img width="367" alt="Screen Shot 2023-03-24 at 15 00 15" src="https://user-images.githubusercontent.com/9611224/227437329-5b83b46d-4c01-4777-b877-af703e409d97.png">

Please check vendor published successfully or not?

**Comment by mohamedsabil83** [comment]
Do you make any changes to how filament generate assets URL?

**Comment by mohamedsabil83** [comment]
Close for not activity. If you still facing this issue, will open it again.
