### ISSUE TITLE
[Bug]: TinyEditor   when drag

### ISSUE THREAD

**Issue by oz-hjx210** [mohamedsabil83/filament-forms-tinyeditor#65]
### What happened?

When I drag a block that contains TinyEditor inside the Builder\Block , TinyEditor loses its content an focus and I am unable to edit it.

### How to reproduce the bug

i dont  know

### Package Version

2.14

### PHP Version

8.2

### Laravel Version

9.0

### Notes

can you help

**Comment by mohamedsabil83** [comment]
This bug was mentioned in #37. it's something related to the editor itself and we are trying to figure out how to fix

**Comment by oz-hjx210** [comment]
Thank you for your contribution with this plugin, and I hope the issue can be fixed soon.
