### ISSUE TITLE
[Bug]: Filament header goes over TinyEditor in fullscreen mode

### ISSUE THREAD

**Issue by reaboivictor** [mohamedsabil83/filament-forms-tinyeditor#66]
### What happened?

When going to full screen, filament header places over the editor:
![image](https://user-images.githubusercontent.com/69897526/230881838-56836436-c426-4142-9600-4cb7eae8cf16.png)

### How to reproduce the bug

1. open full screen

### Package Version

v1.7.1

### PHP Version

8.2.0

### Laravel Version

v9.52.5

### Which operating systems does with happen with?

Windows

**Comment by reaboivictor** [comment]
It might be because here is used **z-0**, and that overrides child's 1200 z-index:

https://github.com/mohamedsabil83/filament-forms-tinyeditor/blob/7e291696ae810eafe2d4047d2701b31b75393bc6/resources/views/tiny-editor.blade.php#L13

**Comment by reaboivictor** [comment]
Yes, it works if I remove **z-0**

![image](https://user-images.githubusercontent.com/69897526/231710390-8898a8a9-0ffe-438a-aced-f622d1b74dde.png)

**Comment by mohamedsabil83** [comment]
then, use it like that in your current project and check it if happened again without overriding the blade file in your next project cause it works fine with me without removing z-0. Maybe you use an old version of admin, create a new theme, or override some package files which make this situation with you.
I'll close this for now and inform me if that's happened again to you with another project.

**Comment by reaboivictor** [comment]
ok, thank you for your support

**Comment by mohamedsabil83** [comment]
You're welcome
