### ISSUE TITLE
[Bug]: CodeMirror caught TypeError: Cannot read properties of undefined (reading 'saveCursorPosition')   

### ISSUE THREAD

**Issue by elfeffe** [mohamedsabil83/filament-forms-tinyeditor#67]
### What happened?

I try to see source code and I get that error

### How to reproduce the bug

Just use codemirror and try to see source code

### Package Version

1.7.1

### PHP Version

8.1

### Laravel Version

v9

### Which operating systems does with happen with?

Linux

**Comment by mohamedsabil83** [comment]
Didn't use code mirror before and there's no information or screenshot, so, can't help you. Anyway, PR is welcome.
