### ISSUE TITLE
[Bug]: Images upload bug on creating post

### ISSUE THREAD

**Issue by slusarsu** [mohamedsabil83/filament-forms-tinyeditor#72]
### What happened?

If I upload an image in the editor when creating a post, I have a problem that the path to the image starts with this "./../storage/upload/", but it should be "/storage/upload/".
If I open the post for editing and re-upload the file in the editor, it works fine.
This means that I have a problem only when creating a post.

### How to reproduce the bug

I sue this construction
TinyEditor::make('content')
                                ->fileAttachmentsDisk('local')
                                ->fileAttachmentsVisibility('storage')
                                ->fileAttachmentsDirectory('public/uploads')
                                

### Package Version

1.7.2

### PHP Version

8.2.3

### Laravel Version

10

**Comment by mohamedsabil83** [comment]
Hi @slusarsu
Sorry for the late reply. I overlooked your issue because I was swamped with work lately
You can use the` ->setConvertUrls(false)` method for your issue.

**Comment by slusarsu** [comment]
Hi @mohamedsabil83 . It is works. Thank you!

**Comment by mohamedsabil83** [comment]
You're welcome 😎
