### ISSUE TITLE
[Bug]: Too many localization asset files

### ISSUE THREAD

**Issue by shirokovnv** [mohamedsabil83/filament-forms-tinyeditor#78]
### What happened?

Hello!

First of all, thank you for your great effort and awesome TinyMCE plugin.

I have more a question rather than a bug: 

Is there a way to reduce the number of publicated assets, especially lang files ? 

To be honest, I dont need all of them. The "eng" will be enough.

Can you provide a solution to optimize publishing?

Thanks!

### How to reproduce the bug

php artisan vendor:publish --tag="filament-forms-tinyeditor-assets"

expected behaviour: 

the number of lang files reduced.

### Package Version

1.7.3

### PHP Version

8.1

### Laravel Version

10.0

**Comment by mohamedsabil83** [comment]
Hello @shirokovnv, thank you for the nice words. I hope you found the package helpful.
The point that you mentioned is one of the other points that I plan to include in the next major version after I have time to work on it.
My primary idea is to publish the **English** translation only. For additional translation, I'll add a new command to publish a selected language. We'll see what the final idea I'm going to implement.

**Comment by shirokovnv** [comment]
Thanks a lot! 
Looking forward to see the next version!
