### ISSUE TITLE
[Bug]: field is cleared when it's a part of a component with drag and drop option

### ISSUE THREAD

**Issue by cisca** [mohamedsabil83/filament-forms-tinyeditor#82]
### What happened?

When TinyEditor used inside a Builder or Repeater Filament component and I drag and drop it the TinyEditor field cleared and can't be edit.

### How to reproduce the bug

Make a Filament Form, put inside Repeater Component and use TinyEditor in this Component. Next make some repeated fields of the Repeater, put some text inside and try to change thier order.

### Package Version

1.7.4

### PHP Version

8.1

### Laravel Version

9

### Which operating systems does with happen with?

Linux

### Notes

Moving the iFrame editor around the DOM is not supported in Tiny. They offer to use remove() and init() instead

**Comment by mohamedsabil83** [comment]
Update the package to the latest version and re-publish the assets like following:
```shell
php artisan vendor:publish --tag=filament-forms-tinyeditor-assets --force
```

**Comment by cisca** [comment]
It helps. Thanks a lot.

**Comment by mohamedsabil83** [comment]
You're welcome. Enjoy
