### ISSUE TITLE
[Bug]: Bug with spatie translatable

### ISSUE THREAD

**Issue by ifedeev** [mohamedsabil83/filament-forms-tinyeditor#83]
### What happened?

after switch language editor can't be opened
![image](https://github.com/mohamedsabil83/filament-forms-tinyeditor/assets/130277787/12d32c34-795f-45fb-a75a-985bef013229)

### How to reproduce the bug

Switch language to another

### Package Version

lates

### PHP Version

8.1

### Laravel Version

10

### Which operating systems does with happen with?

macOS, Windows, Linux

**Comment by mohamedsabil83** [comment]
Do you mean switching **locale** within **config/app.php**?
If so, does the default one, **en**, works as expected?
What about **de**?

**Comment by ifedeev** [comment]
> Do you mean switching **locale** within **config/app.php**? If so, does the default one, **en**, works as expected? What about **de**?

mm, I mean with package filament-translatable - (spatie/translatable)

**Comment by core45** [comment]
I have it with spatie-translatable and it works fine.
@ifedeev: did you install filament/spatie-laravel-translatable-plugin so the Filament is aware of translations?

**Comment by mohamedsabil83** [comment]
@ifedeev We can't reproduce your issue. Many use it and it works fine as @core45 said. Be sure to install everything and configure it as it needs.

**Comment by ifedeev** [comment]
> I have it with spatie-translatable and it works fine. @ifedeev: did you install filament/spatie-laravel-translatable-plugin so the Filament is aware of translations?

yes

**Comment by ifedeev** [comment]
> @ifedeev We can't reproduce your issue. Many use it and it works fine as @core45 said. Be sure to install everything and configure it as it needs.

@mohamedsabil83 I'm use spatie-translatable + Builder

**Comment by mohamedsabil83** [comment]
Can you show me your code? Because it works as expected in my side.

**Comment by ifedeev** [comment]
> Can you show me your code? Because it works as expected in my side.

![image](https://github.com/mohamedsabil83/filament-forms-tinyeditor/assets/130277787/eff281e3-0ebd-497c-a840-b7bffb0fbc5d)
![image](https://github.com/mohamedsabil83/filament-forms-tinyeditor/assets/130277787/6cf25755-c848-4f46-9474-8ccd469795e0)

UI when everything is OK
![image](https://github.com/mohamedsabil83/filament-forms-tinyeditor/assets/130277787/50a2cd1c-2369-4ef6-b4da-a8f566c07c47)

when I switch language 
![image](https://github.com/mohamedsabil83/filament-forms-tinyeditor/assets/130277787/242073e5-a1ed-4c00-8c3f-56d9a94f8354)
![image](https://github.com/mohamedsabil83/filament-forms-tinyeditor/assets/130277787/461b967c-9821-412d-bc1c-86154f0a6dce)

**Comment by mohamedsabil83** [comment]
I guess there are some conflicts with the **PageBuilder** package. Try to use it without **PageBuilder** package to confirm if works as expected or not.

**Comment by justgkp** [comment]
In Filamentor view page, table not rendering properly
<img width="956" alt="Screenshot 2023-08-11 at 2 37 02 AM" src="https://github.com/mohamedsabil83/filament-forms-tinyeditor/assets/71189434/d4bd7b26-fcbc-4ab6-8988-5693edc41f6a">

**Comment by ifedeev** [comment]
> I guess there are some conflicts with the **PageBuilder** package. Try to use it without **PageBuilder** package to confirm if works as expected or not.

Bug only with filament-fabticator + spatie-translatable

**Comment by ifedeev** [comment]
fixed
![image](https://github.com/mohamedsabil83/filament-forms-tinyeditor/assets/130277787/c9c76d7b-af9a-4e42-add1-83998c0e7633)
