### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by core45** [mohamedsabil83/filament-forms-tinyeditor#85]
### What happened?

When the record containing the text is deleted or the photo in the text is removed from it, the photo file remains but it should be deleted.
Maybe the photos and files that are being uploaded could be managed with spatie/medialibrary - would be so much better.

### How to reproduce the bug

just add and remove the photo

### Package Version

2

### PHP Version

8.2

### Laravel Version

10

**Comment by mohamedsabil83** [comment]
The photos uploaded in the editor are not related to a model directly. So, it's your job to deal with that photos.

**Comment by core45** [comment]
What about spatie/medialibrary - maybe this could be a solution?
Something like ->fileAttachmentWithMediaLibrary('collection_name')

**Comment by mohamedsabil83** [comment]
PR are welcome

**Comment by core45** [comment]
Any idea how can I plug into the file storage chain?
