### ISSUE TITLE
[Bug]: [v1.7.5] Uncaught SyntaxError: expected expression, got '<'

### ISSUE THREAD

**Issue by nikspyratos** [mohamedsabil83/filament-forms-tinyeditor#87]
### What happened?

JS errors in the TinyMCE version used in v1.7.5 - had to use that version because v2+ requires Filament v3 and I am on a v2 repo.

<img width="1437" alt="Screenshot 2023-08-10 at 11 43 58" src="https://github.com/mohamedsabil83/filament-forms-tinyeditor/assets/17888779/d09a79ba-b356-4bba-a363-5e86bd87b495">

### How to reproduce the bug

- Use a Filament v2 panel
- `composer require mohamedsabil83/filament-forms-tinyeditor:^1.7.5`

### Package Version

1.7.5

### PHP Version

8.2

### Laravel Version

8.83.27

### Notes

Probably will postpone the need for this until I can just upgrade to V3, but any other lingering v2 users may also have this issue.

**Comment by mohamedsabil83** [comment]
I tried your steps and the editor works as expected. Do you publish assets? Also, do you install it or upgrade it? If upgrade, try to re-publish the assets with `--force` option and check again

**Comment by nikspyratos** [comment]
Publishing seems to fix it. This was a fresh install and not an upgrade though.
