### ISSUE TITLE
[Bug]: Editor in nested repeater breaks after changing the order 

### ISSUE THREAD

**Issue by studiowizjo** [mohamedsabil83/filament-forms-tinyeditor#88]
### What happened?

In a situation where the editor is embedded in a nested repeater field that has a sorting option, after changing the order of the elements, the editor breaks (the content in it disappears and the content area becomes inactive - you can't click on it and write). It seems that it is not being re-initialized correctly.

An example of a form configuration that causes this error:

```php
Repeater::make('questions')
    ->label('FAQ categories')
    ->createItemButtonLabel('Add category')
    ->orderable()
    ->collapsible()
    ->schema([
        TextInput::make('category')
            ->required(),
            
        Repeater::make('questions')
            ->collapsible() 
            ->orderable()
            ->schema([
                TextInput::make('question')
                    ->required(),

                TinyEditor::make('answer')
                    ->required(),
            ])
            ->columns(2)                
    ])
    ->columns(2);
```

### How to reproduce the bug

As above

### Package Version

1.5

### PHP Version

8.1.13

### Laravel Version

9.19

### Which operating systems does with happen with?

Windows

**Comment by mohamedsabil83** [comment]
Try updating to the latest version (**1.7.5**) and force-publish assets.

**Comment by mohamedsabil83** [comment]
I'll close this for now. If you still face it, don't hesitate to re-open.

**Comment by studiowizjo** [comment]
I apologize for the late response - I was on vacation. I can confirm that it works. Thank you =).
