### ISSUE TITLE
[Bug]: Editor in modal break when opened second time

### ISSUE THREAD

**Issue by rahmanramsi** [mohamedsabil83/filament-forms-tinyeditor#89]
### What happened?

![CleanShot 2023-08-18 at 11 18 49](https://github.com/mohamedsabil83/filament-forms-tinyeditor/assets/48276043/a7492202-caec-4d67-ab6f-f1dfa0ecfeeb)

### How to reproduce the bug

- Create an action with modal form.
- Add TinyEditor field inside it.
- Open the modal. it will work as expected.
- Close the modal, and then open again.
- TinyEditor field doesn't work

### Package Version

2.0.1

### PHP Version

8.1.22

### Laravel Version

10.19.0

### Which operating systems does with happen with?

macOS

**Comment by mohamedsabil83** [comment]
Any issues appear in the browser console?

**Comment by olehlong** [comment]
Try this version https://github.com/olehlong/filament-forms-tinyeditor/blob/2.x/resources/views/tiny-editor.blade.php . I have a slightly modified local version in my project, so I'm not sure it will work in the plugin.
Just adding destroy to x-data without Editor variable might work as well 
```
destroy: () => tinymce.get('tiny-editor-{{ $getId() }}')?.remove()
```
but it didn't work in a custom page's action form. Firefox throws an error sometimes, but editor still works every time.

**Comment by mohamedsabil83** [comment]
By saying **it didn't work in a custom page's action form** you mean outside **panel**?

**Comment by olehlong** [comment]
No, inside a panel. Custom resource page [https://filamentphp.com/docs/3.x/panels/resources/custom-pages](https://filamentphp.com/docs/3.x/panels/resources/custom-pages) with a modal form [https://filamentphp.com/docs/3.x/actions/modals#modal-forms](https://filamentphp.com/docs/3.x/actions/modals#modal-forms)

**Comment by mohamedsabil83** [comment]
I just released a new tag. Can you check?

**Comment by rahmanramsi** [comment]
@mohamedsabil83 its working now
