### ISSUE TITLE
[Bug]: TinyEditor field does not appear on production machine

### ISSUE THREAD

**Issue by ksorbo** [mohamedsabil83/filament-forms-tinyeditor#90]
### What happened?

When I commit and pull to my production machine, the TinyEditor fields do not appear. There is space on the screen for them, but they are just blank. (I ran composer update after installation)

**Is it possible that I have not some of the assets needed to display the fields?**

### How to reproduce the bug

I can't see the TinyEditor field on my production machine.

``

### Package Version

1.7.5

### PHP Version

8.1.7

### Laravel Version

10.18.0

### Which operating systems does with happen with?

Linux

**Comment by MarkKhromov** [comment]
Hey, man! Try it: `php artisan vendor:publish --tag="filament-forms-tinyeditor-assets" --force`

**Comment by MarkKhromov** [comment]
@ksorbo Most likely, you looked at the description for the new version, which is intended for Filament 3. Try switching to the 1.x branch instead of 2.x: https://github.com/mohamedsabil83/filament-forms-tinyeditor/tree/1.x
