### ISSUE TITLE
[Bug]: Not properly load with spatie-laravel-translatable-plugin after cople changing languges

### ISSUE THREAD

**Issue by vovacorgo** [mohamedsabil83/filament-forms-tinyeditor#92]
### What happened?

 Not properly load with spatie-laravel-translatable-plugin after cople changing languges  

### How to reproduce the bug

![изображение](https://github.com/mohamedsabil83/filament-forms-tinyeditor/assets/47760619/fa121ea5-07e6-4beb-891c-d740a5f43b09)
when i change language first time works properply, after changing again get empty field:
![изображение](https://github.com/mohamedsabil83/filament-forms-tinyeditor/assets/47760619/b4fab28d-661e-48da-a6f8-ed1febc6d4c7)
and that in console
![изображение](https://github.com/mohamedsabil83/filament-forms-tinyeditor/assets/47760619/de1050e3-f7f0-4fa6-98b1-25e225780ad6)

### Package Version

2

### PHP Version

8.2

### Laravel Version

10

**Comment by mohamedsabil83** [comment]
Yeah, I notice that, but I wonder if that's because of something related to Filament or Livewire. I'll dig it, and PR is also welcome.

**Comment by ysfkaya** [comment]
I'm having the same problem. Any progress?

**Comment by mohamedsabil83** [comment]
Sorry, I'm swamped this period. I'll try to work on it soon.
Also, I noted some developers discussing different issues related to the translatable plugin. As V3 is still new, it'll take time to be stable.

**Comment by mohamedsabil83** [comment]
I just tagged v2.0.3. Can you check?

**Comment by ysfkaya** [comment]
The situation is the same. On the other hand, I will try to solve it. If so, I will let you know.

**Comment by mohamedsabil83** [comment]
Sounds good. I'll close it for now, and you can re-open it if you find something.
btw, I tried it on my side, and it works. Try to check if you publish assets or if something conflicts with them.

**Comment by ysfkaya** [comment]
I think I found the reason for the error. The editor is removing after each component updated and trying to re-init.

`tiny-editor.js`

```js
  Livewire.hook('morph.updated', (el) => {
      if (!window.tinySettingsCopy) {
          return;
      }

      const isModalOpen = document.body.classList.contains('tox-dialog__disable-scroll');

      if (!isModalOpen && sortableClass.some(i => el.el.classList.contains(i))) {
          removeEditors();
          setTimeout(reinitializeEditors, 1);
      }
  })
```

So when I removed the above code it's works well. But It does not working when change the order of element in sortable container.
