### ISSUE TITLE
Error when displaying image on s3 disk

### ISSUE THREAD

**Issue by orebarranco** [mohamedsabil83/filament-forms-tinyeditor#93]
### What happened?

Hello, the error is the following: When an image is uploaded to the s3 disk, it is displayed perfectly while it is in the window. But, once the record is saved and the window is refreshed, the image does not appear.

![image](https://github.com/mohamedsabil83/filament-forms-tinyeditor/assets/106551888/05ea88f0-0207-42f2-8362-4c8c795c1db9)

### How to reproduce the bug

This is the code in the Filamenphp Resource

![image](https://github.com/mohamedsabil83/filament-forms-tinyeditor/assets/106551888/4b5d2a16-8150-4ead-ab2b-f9c6d7577e12)

And that in console

![image](https://github.com/mohamedsabil83/filament-forms-tinyeditor/assets/106551888/06d0662b-7daa-4d18-b85b-3a5ffeed34c6)

Any help?

### Package Version

1.7.5

### PHP Version

8.1.10

### Laravel Version

9.48.0

### Notes

I am using filamentphp v2

**Comment by mohamedsabil83** [comment]
Sorry, I didn't use the **S3** disk, so I'm afraid I can't help you. Can you check the saved path and turn the **relativeURLs ** and/or ** convertURLs** to off? they are both true by default.
- `->setRelativeUrls(false)`
- `->setConvertUrls(false)`

**Comment by mohamedsabil83** [comment]
Due to no response, I'll close it for now. Don't hesitate to re-open it.

**Comment by lloricode** [comment]
hi, try this, put this on service provider

```php
        TinyEditor::configureUsing(
            fn (TinyEditor $component) => $component
                ->fileAttachmentsDirectory('tiny-editor')
                ->fileAttachmentsDisk('s3')
                ->fileAttachmentsVisibility('private')
                ->getUploadedAttachmentUrlUsing(
                    fn (string $file) => config()
                        ->string('filesystems.disks.s3.url').'/'.Str::trim($file)
                )
        );
```
