### ISSUE TITLE
[Bug]: Cannot focus on field inside TinyEditor toolbox modal 

### ISSUE THREAD

**Issue by rahmanramsi** [mohamedsabil83/filament-forms-tinyeditor#98]
### What happened?

https://github.com/mohamedsabil83/filament-forms-tinyeditor/assets/48276043/e30e7564-39ef-4ebd-9a5f-be62a0a8de0c

### How to reproduce the bug

- Create an action with modal form.
- Add TinyEditor field inside it.
- Open the modal.
- Click Link `🔗` toolbox
- New modal with some field will appear
- Click the field, it wont focus on the clicked field

### Package Version

2.0.4

### PHP Version

8.1.22

### Laravel Version

10.25.0

### Which operating systems does with happen with?

macOS

**Comment by mohamedsabil83** [comment]
Fixed in [v2.0.5](https://github.com/mohamedsabil83/filament-forms-tinyeditor/releases/tag/v2.0.5)

**Comment by rahmanramsi** [comment]
Thanks!
